version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7.4
      - image: circleci/postgres:9.6-alpine-ram
    steps:
      - checkout
      - run: sudo apt update && sudo apt install postgresql-client
      - run: whoami
      - run: |
          psql -h localhost -U postgres -d mydb -c "CREATE TABLE test (name char(25));"
      - run: |
          psql -h localhost -U postgres -d mydb -c "INSERT INTO test VALUES ('hello');"
      - run: |
          psql -h localhost -U postgres -d mydb -c "SELECT * FROM test;"
