version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7.4
      - image: circleci/postgres:9.6-alpine-ram
    environment:
      TEST_DATABASE_URL: postgres://postgres@localhost/
    steps:
      - checkout
      - run: sudo apt install postgresql-client
      - run: whoami
      - run: |
          psql -U postgres -c "CREATE DATABASE mydb;"
      - run: |
          psql -U postgres -d mydb -c "CREATE TABLE test (name char(25));"
      - run: |
          psql -U postgres -d mydb -c "INSERT INTO test VALUES ('hello');"
      - run: |
          psql -U postgres -d mydb -c "SELECT * FROM test;"
