version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7.4
      - image: circleci/postgres:9.6-alpine-ram
    environment:
      TEST_DATABASE_URL: postgres://root@localhost/mydb
    steps:
      - checkout
      - run: sudo apt update && sudo apt install -y postgresql-client
      - run: whoami
      - run: |
          psql -d $TEST_DATABASE_URL -c "CREATE TABLE test (name char(25));"
      - run: |
          psql -d $TEST_DATABASE_URL -c "INSERT INTO test VALUES ('hello');"
      - run: |
          psql -d $TEST_DATABASE_URL -c "SELECT * FROM test;"
